<script module lang="ts">
    import { index as reviewIndex } from '@/routes/review';

    export const layout = {
        breadcrumbs: [
            {
                title: 'Review queue',
                href: reviewIndex(),
            },
        ],
    };
</script>

<script lang="ts">
    import { Form, Link } from '@inertiajs/svelte';
    import AppHead from '@/components/AppHead.svelte';
    import Heading from '@/components/Heading.svelte';
    import Pagination from '@/components/Pagination.svelte';
    import StatusBadge from '@/components/StatusBadge.svelte';
    import { Button } from '@/components/ui/button';
    import { csrfToken } from '@/lib/csrf';
    import { formatDateTime } from '@/lib/datetime';
    import { paperlessLabel } from '@/lib/paperless';
    import { toUrl } from '@/lib/utils';
    import { show } from '@/routes/review';
    import type { Paginator } from '@/types';

    type Suggestion = {
        id: number;
        paperless_document_id: number;
        status: string;
        confidence: number | null;
        judge_verdict: string | null;
        original_title: string | null;
        proposed_title: string | null;
        proposed_correspondent_id: number | null;
        proposed_correspondent_name: string | null;
        proposed_document_type_id: number | null;
        proposed_document_type_name: string | null;
        proposed_storage_path_id: number | null;
        proposed_storage_path_name: string | null;
        created_at: string | null;
    };

    let {
        suggestions,
        filters,
        actions,
    }: {
        suggestions: Paginator<Suggestion>;
        filters: Record<string, string | number | null>;
        actions: { index: string; bulkAccept: string; bulkReject: string };
    } = $props();

    let selectedIds = $state<number[]>([]);

    const visibleIds = $derived(
        suggestions.data.map((suggestion) => suggestion.id),
    );
    const allVisibleSelected = $derived(
        visibleIds.length > 0 &&
            visibleIds.every((id) => selectedIds.includes(id)),
    );

    const toggleSelection = (id: number, checked: boolean) => {
        selectedIds = checked
            ? [...new Set([...selectedIds, id])]
            : selectedIds.filter((selectedId) => selectedId !== id);
    };

    const toggleAllVisible = (checked: boolean) => {
        selectedIds = checked
            ? [...new Set([...selectedIds, ...visibleIds])]
            : selectedIds.filter((id) => !visibleIds.includes(id));
    };
</script>

<AppHead title="Review queue" />

<div class="space-y-6">
    <Heading
        title="Review queue"
        description="Fresh ArchiBot review suggestions generated by worker classification."
    />

    <form action={actions.index} method="get" class="register-panel p-4 sm:p-5">
        <div
            class="grid gap-4 lg:grid-cols-[12rem_minmax(16rem,1fr)_auto] lg:items-end"
        >
            <label class="grid gap-1.5 text-sm font-medium">
                Queue
                <select
                    name="status"
                    class="h-11 rounded-md border bg-background px-3 text-sm"
                >
                    {#each ['pending', 'accepted', 'rejected', 'all'] as status (status)}
                        <option
                            value={status}
                            selected={filters.status === status}
                            >{status}</option
                        >
                    {/each}
                </select>
            </label>
            <label class="grid gap-1.5 text-sm font-medium">
                Find a document
                <input
                    name="q"
                    value={filters.q ?? ''}
                    placeholder="Search title or correspondent"
                    class="h-11 rounded-md border bg-background px-3 text-sm"
                />
            </label>
            <div class="flex flex-wrap gap-2">
                <Button type="submit">Apply</Button>
                <Button
                    type="button"
                    variant="outline"
                    onclick={() => (window.location.href = actions.index)}
                    >Clear</Button
                >
            </div>
        </div>

        <details class="mt-4 border-t border-border/80 pt-3">
            <summary
                class="min-h-10 cursor-pointer py-2 text-sm font-medium text-muted-foreground"
            >
                More filters and sorting
            </summary>
            <div class="grid gap-4 pt-3 sm:grid-cols-2 lg:grid-cols-4">
                <label class="grid gap-1.5 text-sm font-medium">
                    Minimum confidence
                    <input
                        name="min_conf"
                        value={filters.min_conf ?? ''}
                        type="number"
                        min="0"
                        max="100"
                        class="h-11 rounded-md border bg-background px-3 text-sm"
                    />
                </label>
                <label class="grid gap-1.5 text-sm font-medium">
                    Maximum confidence
                    <input
                        name="max_conf"
                        value={filters.max_conf ?? ''}
                        type="number"
                        min="0"
                        max="100"
                        class="h-11 rounded-md border bg-background px-3 text-sm"
                    />
                </label>
                <label class="grid gap-1.5 text-sm font-medium">
                    Judge verdict
                    <input
                        name="judge_verdict"
                        value={filters.judge_verdict ?? ''}
                        class="h-11 rounded-md border bg-background px-3 text-sm"
                    />
                </label>
                <label class="grid gap-1.5 text-sm font-medium">
                    Correspondent reference
                    <input
                        name="correspondent_id"
                        value={filters.correspondent_id ?? ''}
                        type="number"
                        min="1"
                        class="h-11 rounded-md border bg-background px-3 text-sm"
                    />
                </label>
                <label class="grid gap-1.5 text-sm font-medium">
                    Storage reference
                    <input
                        name="storage_path_id"
                        value={filters.storage_path_id ?? ''}
                        type="number"
                        min="1"
                        class="h-11 rounded-md border bg-background px-3 text-sm"
                    />
                </label>
                <label class="grid gap-1.5 text-sm font-medium">
                    Items per page
                    <select
                        name="per_page"
                        class="h-11 rounded-md border bg-background px-3 text-sm"
                    >
                        {#each [10, 25, 50, 100] as size (size)}
                            <option
                                value={size}
                                selected={Number(filters.per_page) === size}
                                >{size}</option
                            >
                        {/each}
                    </select>
                </label>
                <label class="grid gap-1.5 text-sm font-medium">
                    Sort order
                    <select
                        name="sort"
                        class="h-11 rounded-md border bg-background px-3 text-sm"
                    >
                        <option
                            value="created_desc"
                            selected={filters.sort === 'created_desc'}
                            >Newest</option
                        >
                        <option
                            value="confidence_asc"
                            selected={filters.sort === 'confidence_asc'}
                            >Lowest confidence</option
                        >
                        <option
                            value="confidence_desc"
                            selected={filters.sort === 'confidence_desc'}
                            >Highest confidence</option
                        >
                    </select>
                </label>
            </div>
        </details>
    </form>

    <section class="register-panel" aria-labelledby="queue-heading">
        <div
            class="flex flex-wrap items-center justify-between gap-3 border-b border-border/80 px-4 py-3 sm:px-5"
        >
            <div class="flex items-center gap-3">
                {#if visibleIds.length > 0}
                    <label
                        class="-m-3 flex size-11 items-center justify-center"
                    >
                        <input
                            type="checkbox"
                            checked={allVisibleSelected}
                            onchange={(event) =>
                                toggleAllVisible(event.currentTarget.checked)}
                            class="size-5"
                        />
                        <span class="sr-only">
                            Select all suggestions on this page
                        </span>
                    </label>
                {/if}
                <div>
                    <h2 id="queue-heading" class="font-semibold">
                        {filters.status === 'pending'
                            ? 'Ready for review'
                            : 'Review register'}
                    </h2>
                    <p class="text-sm text-muted-foreground">
                        {suggestions.total} suggestion{suggestions.total === 1
                            ? ''
                            : 's'}
                    </p>
                </div>
            </div>
            {#if selectedIds.length > 0}
                <div class="flex gap-2">
                    <Form
                        method="post"
                        action={actions.bulkAccept}
                        onsubmit={(event) => {
                            if (
                                !confirm(
                                    `Accept ${selectedIds.length} selected suggestions and queue their Paperless updates?`,
                                )
                            ) {
                                event.preventDefault();
                            }
                        }}
                    >
                        {#snippet children({ processing })}
                            <input
                                type="hidden"
                                name="_token"
                                value={csrfToken()}
                            />
                            {#each selectedIds as id (id)}
                                <input
                                    type="hidden"
                                    name="suggestion_ids[]"
                                    value={id}
                                />
                            {/each}
                            <Button
                                type="submit"
                                size="sm"
                                disabled={processing}
                                >Bulk accept ({selectedIds.length})</Button
                            >
                        {/snippet}
                    </Form>
                    <Form
                        method="post"
                        action={actions.bulkReject}
                        onsubmit={(event) => {
                            if (
                                !confirm(
                                    `Reject ${selectedIds.length} selected suggestions without changing Paperless documents?`,
                                )
                            ) {
                                event.preventDefault();
                            }
                        }}
                    >
                        {#snippet children({ processing })}
                            <input
                                type="hidden"
                                name="_token"
                                value={csrfToken()}
                            />
                            {#each selectedIds as id (id)}
                                <input
                                    type="hidden"
                                    name="suggestion_ids[]"
                                    value={id}
                                />
                            {/each}
                            <Button
                                type="submit"
                                size="sm"
                                variant="outline"
                                disabled={processing}
                                >Bulk reject ({selectedIds.length})</Button
                            >
                        {/snippet}
                    </Form>
                </div>
            {/if}
        </div>

        {#each suggestions.data as suggestion (suggestion.id)}
            <div
                class="register-ledger-row grid gap-3 p-4 sm:p-5 md:grid-cols-[auto_1fr_auto]"
            >
                <label class="-m-3 flex size-11 items-center justify-center">
                    <input
                        type="checkbox"
                        checked={selectedIds.includes(suggestion.id)}
                        onchange={(event) =>
                            toggleSelection(
                                suggestion.id,
                                event.currentTarget.checked,
                            )}
                        class="size-5"
                    />
                    <span class="sr-only">
                        Select review suggestion {suggestion.id}
                    </span>
                </label>
                <div class="space-y-1">
                    <div
                        class="flex flex-wrap items-center gap-2 text-sm text-muted-foreground"
                    >
                        <StatusBadge status={suggestion.status} />
                        <span>Document {suggestion.paperless_document_id}</span>
                        <span
                            >Created {formatDateTime(
                                suggestion.created_at,
                            )}</span
                        >
                        {#if suggestion.confidence !== null}
                            <span>{suggestion.confidence}% confidence</span>
                        {/if}
                        {#if suggestion.judge_verdict}
                            <span>Judge: {suggestion.judge_verdict}</span>
                        {/if}
                    </div>
                    <h3 class="text-base font-semibold tracking-tight">
                        {suggestion.proposed_title ??
                            suggestion.original_title ??
                            'Untitled document'}
                    </h3>
                    <p class="text-sm text-muted-foreground">
                        {paperlessLabel(
                            suggestion.proposed_correspondent_id,
                            suggestion.proposed_correspondent_name,
                        )}
                        · {paperlessLabel(
                            suggestion.proposed_document_type_id,
                            suggestion.proposed_document_type_name,
                        )}
                        · {paperlessLabel(
                            suggestion.proposed_storage_path_id,
                            suggestion.proposed_storage_path_name,
                        )}
                    </p>
                </div>

                <Button variant="outline" asChild>
                    {#snippet children(props)}
                        <Link
                            href={toUrl(show(suggestion.id))}
                            class={props.class}>Review</Link
                        >
                    {/snippet}
                </Button>
            </div>
        {:else}
            <div class="p-8 text-center text-muted-foreground">
                No review suggestions match the current filters.
            </div>
        {/each}
        <Pagination
            links={suggestions.links}
            from={suggestions.from}
            to={suggestions.to}
            total={suggestions.total}
            perPage={suggestions.per_page}
            label="Review queue pages"
        />
    </section>
</div>
