<script module lang="ts">
    import { index as reviewIndex } from '@/routes/review';

    export const layout = {
        breadcrumbs: [
            {
                title: 'Review queue',
                href: reviewIndex(),
            },
        ],
    };
</script>

<script lang="ts">
    import { Link } from '@inertiajs/svelte';
    import AppHead from '@/components/AppHead.svelte';
    import Heading from '@/components/Heading.svelte';
    import { Button } from '@/components/ui/button';
    import { formatDateTime } from '@/lib/datetime';
    import { paperlessLabel } from '@/lib/paperless';
    import { toUrl } from '@/lib/utils';
    import { show } from '@/routes/review';

    type Suggestion = {
        id: number;
        paperless_document_id: number;
        status: string;
        confidence: number | null;
        judge_verdict: string | null;
        original_title: string | null;
        proposed_title: string | null;
        proposed_correspondent_id: number | null;
        proposed_correspondent_name: string | null;
        proposed_document_type_id: number | null;
        proposed_document_type_name: string | null;
        proposed_storage_path_id: number | null;
        proposed_storage_path_name: string | null;
        created_at: string | null;
    };

    type Paginator<T> = {
        data: T[];
        total: number;
    };

    let {
        suggestions,
        filters,
        actions,
    }: {
        suggestions: Paginator<Suggestion>;
        filters: Record<string, string | number | null>;
        actions: { index: string; bulkAccept: string; bulkReject: string };
    } = $props();

    let selectedIds = $state<number[]>([]);

    const csrfToken = () =>
        document
            .querySelector<HTMLMetaElement>('meta[name="csrf-token"]')
            ?.getAttribute('content') ?? '';

    const toggleSelection = (id: number, checked: boolean) => {
        selectedIds = checked
            ? [...new Set([...selectedIds, id])]
            : selectedIds.filter((selectedId) => selectedId !== id);
    };
</script>

<AppHead title="Review queue" />

<div class="space-y-6">
    <Heading
        title="Review queue"
        description="Fresh ArchiBot review suggestions generated by worker classification."
    />

    <form
        action={actions.index}
        method="get"
        class="grid gap-3 rounded-xl border p-4 md:grid-cols-4"
    >
        <select
            name="status"
            class="h-9 rounded-md border bg-background px-3 text-sm"
        >
            {#each ['pending', 'accepted', 'rejected', 'all'] as status (status)}
                <option value={status} selected={filters.status === status}
                    >{status}</option
                >
            {/each}
        </select>
        <input
            name="q"
            value={filters.q ?? ''}
            placeholder="Search title/correspondent"
            class="h-9 rounded-md border bg-background px-3 text-sm"
        />
        <input
            name="min_conf"
            value={filters.min_conf ?? ''}
            type="number"
            min="0"
            max="100"
            placeholder="Min confidence"
            class="h-9 rounded-md border bg-background px-3 text-sm"
        />
        <input
            name="max_conf"
            value={filters.max_conf ?? ''}
            type="number"
            min="0"
            max="100"
            placeholder="Max confidence"
            class="h-9 rounded-md border bg-background px-3 text-sm"
        />
        <input
            name="judge_verdict"
            value={filters.judge_verdict ?? ''}
            placeholder="Judge verdict"
            class="h-9 rounded-md border bg-background px-3 text-sm"
        />
        <input
            name="correspondent_id"
            value={filters.correspondent_id ?? ''}
            type="number"
            min="1"
            placeholder="Correspondent reference"
            class="h-9 rounded-md border bg-background px-3 text-sm"
        />
        <input
            name="storage_path_id"
            value={filters.storage_path_id ?? ''}
            type="number"
            min="1"
            placeholder="Storage reference"
            class="h-9 rounded-md border bg-background px-3 text-sm"
        />
        <select
            name="sort"
            class="h-9 rounded-md border bg-background px-3 text-sm"
        >
            <option
                value="created_desc"
                selected={filters.sort === 'created_desc'}>Newest</option
            >
            <option
                value="confidence_asc"
                selected={filters.sort === 'confidence_asc'}
                >Confidence ascending</option
            >
            <option
                value="confidence_desc"
                selected={filters.sort === 'confidence_desc'}
                >Confidence descending</option
            >
        </select>
        <div class="flex gap-2 md:col-span-4">
            <Button type="submit" size="sm">Apply filters</Button>
            <Button
                type="button"
                size="sm"
                variant="outline"
                onclick={() => (window.location.href = actions.index)}
                >Reset</Button
            >
        </div>
    </form>

    <div class="rounded-xl border">
        <div
            class="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-3 text-sm text-muted-foreground"
        >
            <span
                >{suggestions.total} suggestion{suggestions.total === 1
                    ? ''
                    : 's'}</span
            >
            {#if selectedIds.length > 0}
                <div class="flex gap-2">
                    <form method="post" action={actions.bulkAccept}>
                        <input
                            type="hidden"
                            name="_token"
                            value={csrfToken()}
                        />
                        {#each selectedIds as id (id)}
                            <input
                                type="hidden"
                                name="suggestion_ids[]"
                                value={id}
                            />
                        {/each}
                        <Button type="submit" size="sm"
                            >Bulk accept ({selectedIds.length})</Button
                        >
                    </form>
                    <form method="post" action={actions.bulkReject}>
                        <input
                            type="hidden"
                            name="_token"
                            value={csrfToken()}
                        />
                        {#each selectedIds as id (id)}
                            <input
                                type="hidden"
                                name="suggestion_ids[]"
                                value={id}
                            />
                        {/each}
                        <Button type="submit" size="sm" variant="outline"
                            >Bulk reject ({selectedIds.length})</Button
                        >
                    </form>
                </div>
            {/if}
        </div>

        {#each suggestions.data as suggestion (suggestion.id)}
            <div
                class="grid gap-3 border-b p-4 last:border-b-0 md:grid-cols-[auto_1fr_auto]"
            >
                <input
                    type="checkbox"
                    aria-label={`Select review suggestion ${suggestion.id}`}
                    checked={selectedIds.includes(suggestion.id)}
                    onchange={(event) =>
                        toggleSelection(
                            suggestion.id,
                            event.currentTarget.checked,
                        )}
                    class="mt-1"
                />
                <div class="space-y-1">
                    <div class="text-sm text-muted-foreground">
                        Paperless document reference {suggestion.paperless_document_id}
                        · Created {formatDateTime(suggestion.created_at)}
                        {#if suggestion.confidence !== null}
                            · {suggestion.confidence}% confidence
                        {/if}
                        {#if suggestion.judge_verdict}
                            · Judge: {suggestion.judge_verdict}
                        {/if}
                        · {suggestion.status}
                    </div>
                    <h2 class="font-medium">
                        {suggestion.proposed_title ??
                            suggestion.original_title ??
                            'Untitled document'}
                    </h2>
                    <p class="text-sm text-muted-foreground">
                        {paperlessLabel(
                            suggestion.proposed_correspondent_id,
                            suggestion.proposed_correspondent_name,
                        )}
                        · {paperlessLabel(
                            suggestion.proposed_document_type_id,
                            suggestion.proposed_document_type_name,
                        )}
                        · {paperlessLabel(
                            suggestion.proposed_storage_path_id,
                            suggestion.proposed_storage_path_name,
                        )}
                    </p>
                </div>

                <Button variant="outline" asChild>
                    {#snippet children(props)}
                        <Link
                            href={toUrl(show(suggestion.id))}
                            class={props.class}>Review</Link
                        >
                    {/snippet}
                </Button>
            </div>
        {:else}
            <div class="p-8 text-center text-muted-foreground">
                No review suggestions match the current filters.
            </div>
        {/each}
    </div>
</div>
