<script module lang="ts">
    import { index as reviewIndex } from '@/routes/review';

    export const layout = {
        breadcrumbs: [
            {
                title: 'Review queue',
                href: reviewIndex(),
            },
        ],
    };
</script>

<script lang="ts">
    import { Link } from '@inertiajs/svelte';
    import AppHead from '@/components/AppHead.svelte';
    import Heading from '@/components/Heading.svelte';
    import { Button } from '@/components/ui/button';
    import { toUrl } from '@/lib/utils';
    import { show } from '@/routes/review';

    type Suggestion = {
        id: number;
        paperless_document_id: number;
        confidence: number | null;
        original_title: string | null;
        proposed_title: string | null;
        proposed_correspondent_name: string | null;
        proposed_document_type_name: string | null;
        created_at: string | null;
    };

    type Paginator<T> = {
        data: T[];
        total: number;
    };

    let { suggestions }: { suggestions: Paginator<Suggestion> } = $props();
</script>

<AppHead title="Review queue" />

<div class="space-y-6">
    <Heading
        title="Review queue"
        description="Fresh ArchiBot review suggestions generated by worker classification."
    />

    <div class="rounded-xl border">
        <div class="border-b px-4 py-3 text-sm text-muted-foreground">
            {suggestions.total} pending suggestion{suggestions.total === 1
                ? ''
                : 's'}
        </div>

        {#each suggestions.data as suggestion (suggestion.id)}
            <div
                class="grid gap-3 border-b p-4 last:border-b-0 md:grid-cols-[1fr_auto]"
            >
                <div class="space-y-1">
                    <div class="text-sm text-muted-foreground">
                        Paperless document #{suggestion.paperless_document_id}
                        {#if suggestion.confidence !== null}
                            · {suggestion.confidence}% confidence
                        {/if}
                    </div>
                    <h2 class="font-medium">
                        {suggestion.proposed_title ??
                            suggestion.original_title ??
                            'Untitled document'}
                    </h2>
                    <p class="text-sm text-muted-foreground">
                        {suggestion.proposed_correspondent_name ??
                            'No correspondent suggested'}
                        · {suggestion.proposed_document_type_name ??
                            'No document type suggested'}
                    </p>
                </div>

                <Button variant="outline" asChild>
                    {#snippet children(props)}
                        <Link
                            href={toUrl(show(suggestion.id))}
                            class={props.class}
                        >
                            Review
                        </Link>
                    {/snippet}
                </Button>
            </div>
        {:else}
            <div class="p-8 text-center text-muted-foreground">
                No pending review suggestions yet.
            </div>
        {/each}
    </div>
</div>
