<?php

return [
    'import_paths' => [
        env('ARCHIBOT_LEGACY_CONFIG_PATH', '/data/config.env'),
    ],

    'definitions' => [
        'paperless.url' => [
            'legacy' => 'paperless_url',
            'group' => 'Paperless',
            'label' => 'Paperless-NGX URL',
            'type' => 'url',
            'default' => '',
            'required' => true,
            'help' => 'Single global Paperless-NGX server for this ArchiBot instance.',
        ],
        'paperless.inbox_tag_id' => [
            'legacy' => 'paperless_inbox_tag_id',
            'group' => 'Paperless',
            'label' => 'Inbox tag ID',
            'type' => 'number',
            'default' => '0',
            'help' => 'Paperless tag ID used as inbox.',
        ],
        'paperless.processed_tag_id' => [
            'legacy' => 'paperless_processed_tag_id',
            'group' => 'Paperless',
            'label' => 'Processed tag ID',
            'type' => 'number',
            'default' => '',
            'help' => 'Optional Paperless tag added after commit.',
        ],
        'paperless.keep_inbox_tag' => [
            'legacy' => 'keep_inbox_tag',
            'group' => 'Paperless',
            'label' => 'Keep inbox tag',
            'type' => 'bool',
            'default' => '1',
        ],

        'ollama.url' => [
            'legacy' => 'ollama_url',
            'group' => 'Ollama',
            'label' => 'Ollama URL',
            'type' => 'url',
            'default' => 'http://ollama:11434',
            'help' => 'Base URL of the Ollama server.',
        ],
        'ollama.timeout_seconds' => [
            'legacy' => 'ollama_timeout_seconds',
            'group' => 'Ollama',
            'label' => 'Timeout seconds',
            'type' => 'number',
            'default' => '600',
        ],
        'ollama.model_swap_delay' => [
            'legacy' => 'ollama_model_swap_delay',
            'group' => 'Ollama',
            'label' => 'Model swap delay seconds',
            'type' => 'number',
            'default' => '8',
        ],

        'ocr.mode' => [
            'legacy' => 'ocr_mode',
            'group' => 'OCR',
            'label' => 'OCR mode',
            'type' => 'select',
            'options' => ['off', 'text', 'vision_light', 'vision_full'],
            'default' => 'off',
        ],
        'ocr.requested_tag_id' => [
            'legacy' => 'ocr_requested_tag_id',
            'group' => 'OCR',
            'label' => 'OCR requested tag ID',
            'type' => 'number',
            'default' => '0',
        ],
        'ocr.text_model' => [
            'legacy' => 'ollama_ocr_model',
            'group' => 'OCR',
            'label' => 'OCR text model',
            'type' => 'text',
            'default' => 'qwen3:4b',
        ],
        'ocr.vision_model' => [
            'legacy' => 'ocr_vision_model',
            'group' => 'OCR',
            'label' => 'OCR vision model',
            'type' => 'text',
            'default' => 'qwen3-vl:4b',
        ],
        'ocr.vision_max_pages' => [
            'legacy' => 'ocr_vision_max_pages',
            'group' => 'OCR',
            'label' => 'Vision max pages',
            'type' => 'number',
            'default' => '3',
        ],
        'ocr.vision_dpi' => [
            'legacy' => 'ocr_vision_dpi',
            'group' => 'OCR',
            'label' => 'Vision DPI',
            'type' => 'number',
            'default' => '150',
        ],
        'ocr.context_window' => [
            'legacy' => 'ollama_ocr_num_ctx',
            'group' => 'OCR',
            'label' => 'OCR context window',
            'type' => 'number',
            'default' => '12288',
        ],
        'ocr.auto_write_back' => [
            'legacy' => null,
            'group' => 'OCR',
            'label' => 'Automatically write approved OCR text to Paperless',
            'type' => 'bool',
            'default' => '0',
            'help' => 'Danger: when enabled, ArchiBot writes generated OCR text to Paperless immediately after creating an OCR review. Original content is still preserved for restore. This is global for now and should become Paperless-account scoped before multi-user deployments.',
        ],

        'embedding.model' => [
            'legacy' => 'ollama_embed_model',
            'group' => 'Embedding',
            'label' => 'Embedding model',
            'type' => 'text',
            'default' => 'qwen3-embedding:4b',
        ],
        'embedding.dimension' => [
            'legacy' => 'ollama_embed_dim',
            'group' => 'Embedding',
            'label' => 'Embedding dimension',
            'type' => 'number',
            'default' => '0',
        ],
        'embedding.context_window' => [
            'legacy' => 'ollama_embed_num_ctx',
            'group' => 'Embedding',
            'label' => 'Embedding context window',
            'type' => 'number',
            'default' => '8192',
        ],
        'embedding.max_chars' => [
            'legacy' => 'embed_max_chars',
            'group' => 'Embedding',
            'label' => 'Max document chars for embedding',
            'type' => 'number',
            'default' => '6000',
        ],
        'embedding.hybrid_search_weight' => [
            'legacy' => 'hybrid_search_weight',
            'group' => 'Embedding',
            'label' => 'Hybrid search weight',
            'type' => 'number',
            'default' => '0.7',
            'min' => '0',
            'max' => '1',
            'step' => '0.1',
            'help' => 'Blend ratio: 0.0 = keyword only, 1.0 = vector only, 0.7 = default.',
        ],

        'classification.model' => [
            'legacy' => 'ollama_model',
            'group' => 'Classification / Review',
            'label' => 'Classification model',
            'type' => 'text',
            'default' => 'gemma4:e4b',
        ],
        'classification.context_window' => [
            'legacy' => 'ollama_num_ctx',
            'group' => 'Classification / Review',
            'label' => 'Classification context window',
            'type' => 'number',
            'default' => '16384',
        ],
        'classification.max_tags' => [
            'legacy' => 'classification_max_tags',
            'group' => 'Classification / Review',
            'label' => 'Max tags',
            'type' => 'number',
            'default' => '4',
        ],
        'classification.max_doc_chars' => [
            'legacy' => 'max_doc_chars',
            'group' => 'Classification / Review',
            'label' => 'Max document chars',
            'type' => 'number',
            'default' => '24000',
        ],
        'classification.context_max_docs' => [
            'legacy' => 'context_max_docs',
            'group' => 'Classification / Review',
            'label' => 'Context max docs',
            'type' => 'number',
            'default' => '5',
        ],
        'classification.context_max_distance' => [
            'legacy' => 'context_max_distance',
            'group' => 'Classification / Review',
            'label' => 'Context max distance',
            'type' => 'number',
            'default' => '0.5',
        ],
        'classification.auto_commit_confidence' => [
            'legacy' => 'auto_commit_confidence',
            'group' => 'Classification / Review',
            'label' => 'Auto-commit confidence',
            'type' => 'number',
            'default' => '0',
            'help' => '0 means always review manually.',
        ],
        'classification.enable_judge_verification' => [
            'legacy' => 'enable_judge_verification',
            'group' => 'Classification / Review',
            'label' => 'Enable judge verification',
            'type' => 'bool',
            'default' => '0',
        ],
        'classification.judge_confidence_threshold' => [
            'legacy' => 'judge_confidence_threshold',
            'group' => 'Classification / Review',
            'label' => 'Judge confidence threshold',
            'type' => 'number',
            'default' => '101',
        ],
        'classification.judge_model' => [
            'legacy' => 'ollama_judge_model',
            'group' => 'Classification / Review',
            'label' => 'Judge model',
            'type' => 'text',
            'default' => 'qwen3:4b',
        ],

        'worker.poll_interval_seconds' => [
            'legacy' => 'poll_interval_seconds',
            'group' => 'Worker',
            'label' => 'Poll interval seconds',
            'type' => 'number',
            'default' => '0',
            'help' => '0 disables scheduled polling.',
        ],

        'webhook.secret' => [
            'legacy' => 'webhook_secret',
            'group' => 'Webhook',
            'label' => 'Webhook secret',
            'type' => 'password',
            'default' => '',
            'sensitive' => true,
            'help' => 'Write-only after saving. Leave blank to keep the current value.',
        ],
        'webhook.log_raw_body' => [
            'legacy' => 'webhook_log_raw_body',
            'group' => 'Webhook',
            'label' => 'Log raw webhook body',
            'type' => 'bool',
            'default' => '0',
        ],

        'mcp.transport' => [
            'legacy' => 'mcp_transport',
            'group' => 'MCP',
            'label' => 'Transport',
            'type' => 'select',
            'options' => ['stdio', 'sse', 'streamable-http'],
            'default' => 'stdio',
        ],
        'mcp.port' => [
            'legacy' => 'mcp_port',
            'group' => 'MCP',
            'label' => 'Port',
            'type' => 'number',
            'default' => '3001',
        ],
        'mcp.host' => [
            'legacy' => 'mcp_host',
            'group' => 'MCP',
            'label' => 'Host',
            'type' => 'text',
            'default' => '0.0.0.0',
        ],
        'mcp.enable_write' => [
            'legacy' => 'mcp_enable_write',
            'group' => 'MCP',
            'label' => 'Enable write tools',
            'type' => 'bool',
            'default' => '0',
            'help' => 'Global kill switch; user MCP tokens will be added separately.',
        ],
        'mcp.classify_rate_limit' => [
            'legacy' => 'mcp_classify_rate_limit',
            'group' => 'MCP',
            'label' => 'Classify rate limit per hour',
            'type' => 'number',
            'default' => '10',
        ],

        'audit.retention_days' => [
            'legacy' => null,
            'group' => 'Audit',
            'label' => 'Audit retention days',
            'type' => 'number',
            'default' => '7',
        ],
    ],
];
