<?php

return [
    'import_paths' => [
        env('ARCHIBOT_LEGACY_CONFIG_PATH', '/data/config.env'),
    ],

    'definitions' => [
        'paperless.url' => [
            'legacy' => 'paperless_url',
            'group' => 'Paperless',
            'label' => 'Paperless-NGX URL',
            'type' => 'url',
            'default' => '',
            'required' => true,
            'help' => 'Single global Paperless-NGX server for this ArchiBot instance.',
        ],
        'paperless.inbox_tag_id' => [
            'legacy' => 'paperless_inbox_tag_id',
            'group' => 'Paperless',
            'label' => 'Inbox tag ID',
            'type' => 'number',
            'default' => '0',
            'help' => 'Paperless tag ID used as inbox.',
        ],
        'paperless.processed_tag_id' => [
            'legacy' => 'paperless_processed_tag_id',
            'group' => 'Paperless',
            'label' => 'Processed tag ID',
            'type' => 'number',
            'default' => '',
            'help' => 'Optional Paperless tag added after commit.',
        ],
        'paperless.keep_inbox_tag' => [
            'legacy' => 'keep_inbox_tag',
            'group' => 'Paperless',
            'label' => 'Keep inbox tag',
            'type' => 'bool',
            'default' => '1',
        ],

        'llm.provider' => [
            'legacy' => 'llm_provider',
            'group' => 'AI Provider',
            'label' => 'Provider',
            'type' => 'select',
            'options' => ['ollama', 'openai_compatible'],
            'default' => 'ollama',
            'help' => 'ollama uses the native Ollama API; openai_compatible uses a local OpenAI-compatible /v1 API.',
        ],
        'ollama.url' => [
            'legacy' => 'ollama_url',
            'group' => 'AI Provider',
            'label' => 'Base URL',
            'type' => 'url',
            'default' => 'http://ollama:11434',
            'help' => 'Ollama base URL for native mode, or OpenAI-compatible base URL including /v1.',
        ],
        'llm.openai_api_key' => [
            'legacy' => 'openai_api_key',
            'group' => 'AI Provider',
            'label' => 'OpenAI-compatible API key',
            'type' => 'password',
            'default' => '',
            'sensitive' => true,
            'help' => 'Optional bearer token for OpenAI-compatible local providers.',
        ],
        'llm.provider_profiles' => [
            'legacy' => 'ai_provider_profiles',
            'group' => 'AI Provider',
            'label' => 'Additional provider profiles (JSON)',
            'type' => 'textarea',
            'default' => '',
            'help' => 'Optional JSON array of named providers. Prefer api_key_env for secrets. Example: [{"id":"local-litellm","type":"openai_compatible","base_url":"http://litellm:4000/v1"},{"id":"openrouter","type":"openai_compatible","base_url":"https://openrouter.ai/api/v1","api_key_env":"OPENROUTER_API_KEY","is_cloud":true}]',
        ],
        'llm.classification_provider' => [
            'legacy' => 'classification_provider',
            'group' => 'AI Provider',
            'label' => 'Classification provider ID',
            'type' => 'text',
            'default' => '',
            'help' => 'Provider profile ID for classification. Empty/default uses the main provider.',
        ],
        'llm.embedding_provider' => [
            'legacy' => 'embedding_provider',
            'group' => 'AI Provider',
            'label' => 'Embedding provider ID',
            'type' => 'text',
            'default' => '',
            'help' => 'Provider profile ID for embeddings. Keep local unless you intentionally allow document text to leave your machine.',
        ],
        'llm.ocr_provider' => [
            'legacy' => 'ocr_provider',
            'group' => 'AI Provider',
            'label' => 'OCR provider ID',
            'type' => 'text',
            'default' => '',
            'help' => 'Provider profile ID for OCR text/vision calls.',
        ],
        'llm.judge_provider' => [
            'legacy' => 'judge_provider',
            'group' => 'AI Provider',
            'label' => 'Judge provider ID',
            'type' => 'text',
            'default' => '',
            'help' => 'Provider profile ID for judge verification. Cloud providers may receive document text.',
        ],
        'llm.chat_provider' => [
            'legacy' => 'chat_provider',
            'group' => 'AI Provider',
            'label' => 'Chat/RAG provider ID',
            'type' => 'text',
            'default' => '',
            'help' => 'Provider profile ID for conversational chat/RAG.',
        ],
        'ollama.timeout_seconds' => [
            'legacy' => 'ollama_timeout_seconds',
            'group' => 'AI Provider',
            'label' => 'Timeout seconds',
            'type' => 'number',
            'default' => '600',
        ],
        'ollama.model_swap_delay' => [
            'legacy' => 'ollama_model_swap_delay',
            'group' => 'AI Provider',
            'label' => 'Ollama model swap delay seconds',
            'type' => 'number',
            'default' => '8',
        ],

        'ocr.mode' => [
            'legacy' => 'ocr_mode',
            'group' => 'OCR',
            'label' => 'OCR mode',
            'type' => 'select',
            'options' => ['off', 'text', 'vision_light', 'vision_full'],
            'default' => 'off',
        ],
        'ocr.requested_tag_id' => [
            'legacy' => 'ocr_requested_tag_id',
            'group' => 'OCR',
            'label' => 'OCR requested tag ID',
            'type' => 'number',
            'default' => '0',
        ],
        'ocr.text_model' => [
            'legacy' => 'ollama_ocr_model',
            'group' => 'OCR',
            'label' => 'OCR text model',
            'type' => 'text',
            'default' => 'qwen3:4b',
        ],
        'ocr.vision_model' => [
            'legacy' => 'ocr_vision_model',
            'group' => 'OCR',
            'label' => 'OCR vision model',
            'type' => 'text',
            'default' => 'qwen3-vl:4b',
        ],
        'ocr.vision_max_pages' => [
            'legacy' => 'ocr_vision_max_pages',
            'group' => 'OCR',
            'label' => 'Vision max pages',
            'type' => 'number',
            'default' => '3',
        ],
        'ocr.vision_dpi' => [
            'legacy' => 'ocr_vision_dpi',
            'group' => 'OCR',
            'label' => 'Vision DPI',
            'type' => 'number',
            'default' => '150',
        ],
        'ocr.context_window' => [
            'legacy' => 'ollama_ocr_num_ctx',
            'group' => 'OCR',
            'label' => 'OCR context window',
            'type' => 'number',
            'default' => '12288',
        ],
        'ocr.auto_write_back' => [
            'legacy' => null,
            'group' => 'OCR',
            'label' => 'Automatically write approved OCR text to Paperless',
            'type' => 'bool',
            'default' => '0',
            'help' => 'Danger: when enabled, ArchiBot writes generated OCR text to Paperless immediately after creating an OCR review. Original content is still preserved for restore. This is global for now and should become Paperless-account scoped before multi-user deployments.',
        ],

        'embedding.model' => [
            'legacy' => 'ollama_embed_model',
            'group' => 'Embedding',
            'label' => 'Embedding model',
            'type' => 'text',
            'default' => 'qwen3-embedding:4b',
        ],
        'embedding.dimension' => [
            'legacy' => 'ollama_embed_dim',
            'group' => 'Embedding',
            'label' => 'Embedding dimension',
            'type' => 'number',
            'default' => '0',
        ],
        'embedding.context_window' => [
            'legacy' => 'ollama_embed_num_ctx',
            'group' => 'Embedding',
            'label' => 'Embedding context window',
            'type' => 'number',
            'default' => '8192',
        ],
        'embedding.max_chars' => [
            'legacy' => 'embed_max_chars',
            'group' => 'Embedding',
            'label' => 'Max document chars for embedding',
            'type' => 'number',
            'default' => '6000',
        ],
        'embedding.hybrid_search_weight' => [
            'legacy' => 'hybrid_search_weight',
            'group' => 'Embedding',
            'label' => 'Hybrid search weight',
            'type' => 'number',
            'default' => '0.7',
            'min' => '0',
            'max' => '1',
            'step' => '0.1',
            'help' => 'Blend ratio: 0.0 = keyword only, 1.0 = vector only, 0.7 = default.',
        ],

        'classification.model' => [
            'legacy' => 'ollama_model',
            'group' => 'Classification / Review',
            'label' => 'Classification model',
            'type' => 'text',
            'default' => 'gemma4:e4b',
        ],
        'classification.context_window' => [
            'legacy' => 'ollama_num_ctx',
            'group' => 'Classification / Review',
            'label' => 'Classification context window',
            'type' => 'number',
            'default' => '16384',
        ],
        'classification.max_tags' => [
            'legacy' => 'classification_max_tags',
            'group' => 'Classification / Review',
            'label' => 'Max tags',
            'type' => 'number',
            'default' => '4',
        ],
        'classification.max_doc_chars' => [
            'legacy' => 'max_doc_chars',
            'group' => 'Classification / Review',
            'label' => 'Max document chars',
            'type' => 'number',
            'default' => '24000',
        ],
        'classification.context_max_docs' => [
            'legacy' => 'context_max_docs',
            'group' => 'Classification / Review',
            'label' => 'Context max docs',
            'type' => 'number',
            'default' => '5',
        ],
        'classification.context_max_distance' => [
            'legacy' => 'context_max_distance',
            'group' => 'Classification / Review',
            'label' => 'Context max distance',
            'type' => 'number',
            'default' => '0.5',
        ],
        'classification.auto_commit_confidence' => [
            'legacy' => 'auto_commit_confidence',
            'group' => 'Classification / Review',
            'label' => 'Auto-commit confidence',
            'type' => 'number',
            'default' => '0',
            'help' => '0 means always review manually.',
        ],
        'classification.enable_judge_verification' => [
            'legacy' => 'enable_judge_verification',
            'group' => 'Classification / Review',
            'label' => 'Enable judge verification',
            'type' => 'bool',
            'default' => '0',
        ],
        'classification.judge_confidence_threshold' => [
            'legacy' => 'judge_confidence_threshold',
            'group' => 'Classification / Review',
            'label' => 'Judge confidence threshold',
            'type' => 'number',
            'default' => '101',
        ],
        'classification.judge_model' => [
            'legacy' => 'ollama_judge_model',
            'group' => 'Classification / Review',
            'label' => 'Judge model',
            'type' => 'text',
            'default' => 'qwen3:4b',
        ],

        'worker.poll_interval_seconds' => [
            'legacy' => 'poll_interval_seconds',
            'group' => 'Worker',
            'label' => 'Poll interval seconds',
            'type' => 'number',
            'default' => '0',
            'help' => '0 disables scheduled polling.',
        ],

        'gui.base_url' => [
            'legacy' => 'gui_base_url',
            'group' => 'GUI',
            'label' => 'External base URL',
            'type' => 'url',
            'default' => '',
            'help' => 'Public ArchiBot URL used in Telegram review links. Leave empty to let Python fall back to localhost and GUI_PORT.',
        ],

        'telegram.enable' => [
            'legacy' => 'enable_telegram',
            'group' => 'Telegram',
            'label' => 'Enable Telegram notifications',
            'type' => 'bool',
            'default' => '0',
            'help' => 'Optional notification and inline approval channel. Laravel web review remains canonical.',
        ],
        'telegram.bot_token' => [
            'legacy' => 'telegram_bot_token',
            'group' => 'Telegram',
            'label' => 'Bot token',
            'type' => 'password',
            'default' => '',
            'sensitive' => true,
            'help' => 'Telegram Bot API token from @BotFather. Write-only after saving.',
        ],
        'telegram.chat_id' => [
            'legacy' => 'telegram_chat_id',
            'group' => 'Telegram',
            'label' => 'Chat ID',
            'type' => 'text',
            'default' => '',
            'help' => 'Telegram chat or group ID for ArchiBot notifications.',
        ],
        'telegram.poll_interval' => [
            'legacy' => 'telegram_poll_interval',
            'group' => 'Telegram',
            'label' => 'Poll interval seconds',
            'type' => 'number',
            'default' => '5',
            'help' => 'Seconds between Telegram getUpdates calls.',
        ],

        'webhook.secret' => [
            'legacy' => 'webhook_secret',
            'group' => 'Webhook',
            'label' => 'Webhook secret',
            'type' => 'password',
            'default' => '',
            'sensitive' => true,
            'help' => 'Write-only after saving. Leave blank to keep the current value.',
        ],
        'webhook.log_raw_body' => [
            'legacy' => 'webhook_log_raw_body',
            'group' => 'Webhook',
            'label' => 'Log raw webhook body',
            'type' => 'bool',
            'default' => '0',
        ],

        'mcp.transport' => [
            'legacy' => 'mcp_transport',
            'group' => 'MCP',
            'label' => 'Transport',
            'type' => 'select',
            'options' => ['stdio', 'sse', 'streamable-http'],
            'default' => 'stdio',
        ],
        'mcp.port' => [
            'legacy' => 'mcp_port',
            'group' => 'MCP',
            'label' => 'Port',
            'type' => 'number',
            'default' => '3001',
        ],
        'mcp.host' => [
            'legacy' => 'mcp_host',
            'group' => 'MCP',
            'label' => 'Host',
            'type' => 'text',
            'default' => '0.0.0.0',
        ],
        'mcp.enable_write' => [
            'legacy' => 'mcp_enable_write',
            'group' => 'MCP',
            'label' => 'Enable write tools',
            'type' => 'bool',
            'default' => '0',
            'help' => 'Global kill switch for mutating MCP tools. Per-user Laravel MCP tokens are managed under /settings/mcp-tokens.',
        ],
        'mcp.api_key' => [
            'legacy' => 'mcp_api_key',
            'group' => 'MCP',
            'label' => 'Legacy API key',
            'type' => 'password',
            'default' => '',
            'sensitive' => true,
            'help' => 'Legacy static MCP auth key. Prefer Laravel-managed per-user MCP tokens. Write-only after saving.',
        ],
        'mcp.laravel_auth_enabled' => [
            'legacy' => 'mcp_laravel_auth_enabled',
            'group' => 'MCP',
            'label' => 'Use Laravel MCP tokens',
            'type' => 'bool',
            'default' => '1',
            'help' => 'Validate MCP tool tokens through Laravel archibot:mcp-token-verify.',
        ],
        'mcp.laravel_path' => [
            'legacy' => 'mcp_laravel_path',
            'group' => 'MCP',
            'label' => 'Laravel app path',
            'type' => 'text',
            'default' => '/app/laravel',
            'help' => 'Path to the Laravel app used by the Python MCP runtime for local token verification.',
        ],
        'mcp.laravel_php_binary' => [
            'legacy' => 'mcp_laravel_php_binary',
            'group' => 'MCP',
            'label' => 'Laravel PHP binary',
            'type' => 'text',
            'default' => 'php',
            'help' => 'PHP executable used by the Python MCP runtime to run the Laravel token verifier.',
        ],
        'mcp.classify_rate_limit' => [
            'legacy' => 'mcp_classify_rate_limit',
            'group' => 'MCP',
            'label' => 'Classify rate limit per hour',
            'type' => 'number',
            'default' => '10',
        ],

        'audit.retention_days' => [
            'legacy' => null,
            'group' => 'Audit',
            'label' => 'Audit retention days',
            'type' => 'number',
            'default' => '7',
        ],
    ],
];
