<?php

return [
    'import_paths' => [
        env('ARCHIBOT_LEGACY_CONFIG_PATH', '/data/config.env'),
    ],

    'definitions' => [
        'paperless.url' => [
            'legacy' => 'paperless_url',
            'group' => 'Paperless',
            'label' => 'Paperless-NGX URL',
            'type' => 'url',
            'default' => '',
            'required' => true,
            'read_only' => true,
            'help' => 'Pinned by the deployment PAPERLESS_URL. Stored or submitted overrides are not used.',
        ],
        'paperless.inbox_tag_id' => [
            'legacy' => 'paperless_inbox_tag_id',
            'group' => 'Paperless',
            'label' => 'Inbox tag',
            'type' => 'number',
            'entity' => 'paperless_tag',
            'default' => '0',
            'help' => 'Paperless tag used as inbox. Display as Label (#ID); never expose a bare numeric tag ID in the GUI.',
        ],
        'paperless.processed_tag_id' => [
            'legacy' => 'paperless_processed_tag_id',
            'group' => 'Paperless',
            'label' => 'Processed tag',
            'type' => 'number',
            'entity' => 'paperless_tag',
            'default' => '',
            'help' => 'Optional Paperless tag added after commit.',
        ],
        'paperless.keep_inbox_tag' => [
            'legacy' => 'keep_inbox_tag',
            'group' => 'Paperless',
            'label' => 'Keep inbox tag',
            'type' => 'bool',
            'default' => '1',
        ],
        'paperless.ai_suggest_enabled' => [
            'legacy' => 'paperless_ai_suggest_enabled',
            'group' => 'Paperless AI',
            'label' => 'Enable manual Paperless AI Suggest',
            'type' => 'bool',
            'default' => '1',
        ],
        'paperless.ai_similar_documents_enabled' => [
            'legacy' => 'paperless_ai_similar_documents_enabled',
            'group' => 'Paperless AI',
            'label' => 'Enable similar Paperless documents',
            'type' => 'bool',
            'default' => '0',
            'help' => 'Stays disabled while a Paperless LLM_INDEX task is active.',
        ],
        'paperless.ai_auto_manage_workflows' => [
            'legacy' => 'paperless_ai_auto_manage_workflows',
            'group' => 'Paperless AI',
            'label' => 'Automatically configure Paperless workflows',
            'type' => 'bool',
            'default' => '1',
        ],
        'paperless.ai_bearer_key' => [
            'legacy' => 'paperless_ai_bearer_key',
            'group' => 'Paperless AI',
            'label' => 'Paperless AI bearer key',
            'type' => 'password',
            'default' => '',
            'sensitive' => true,
            'help' => 'Dedicated bearer key for the restricted Paperless AI Suggest adapter. Write-only after saving.',
        ],
        'paperless.ai_endpoint_timeout_seconds' => [
            'legacy' => 'paperless_ai_timeout_seconds',
            'group' => 'Paperless AI',
            'label' => 'Manual Suggest timeout seconds',
            'type' => 'number',
            'default' => '120',
        ],
        'paperless.ai_model_override' => [
            'legacy' => 'paperless_ai_model_override',
            'group' => 'Paperless AI',
            'label' => 'Paperless Suggest model override',
            'type' => 'text',
            'default' => '',
            'help' => 'Leave blank to inherit the normal classification model.',
        ],
        'paperless.ai_prompt_role' => [
            'legacy' => 'paperless_ai_prompt_role',
            'group' => 'Paperless AI',
            'label' => 'Paperless Suggest prompt role',
            'type' => 'text',
            'default' => 'paperless_suggest',
            'read_only' => true,
        ],

        'llm.provider' => [
            'legacy' => 'llm_provider',
            'group' => 'AI Provider',
            'label' => 'Provider',
            'type' => 'select',
            'options' => ['ollama', 'openai_compatible'],
            'default' => 'ollama',
            'help' => 'ollama uses an Ollama-compatible API; openai_compatible uses an OpenAI-compatible /v1 API.',
        ],
        'ollama.url' => [
            'legacy' => 'ollama_url',
            'group' => 'AI Provider',
            'label' => 'Base URL',
            'type' => 'url',
            'default' => 'http://ollama:11434',
            'help' => 'Ollama base URL for native mode, or OpenAI-compatible base URL including /v1.',
        ],
        'llm.openai_api_key' => [
            'legacy' => 'openai_api_key',
            'group' => 'AI Provider',
            'label' => 'OpenAI-compatible API key',
            'type' => 'password',
            'default' => '',
            'sensitive' => true,
            'help' => 'Optional bearer token for OpenAI-compatible providers.',
        ],
        'ollama.timeout_seconds' => [
            'legacy' => 'ollama_timeout_seconds',
            'group' => 'AI Provider',
            'label' => 'Timeout seconds',
            'type' => 'number',
            'default' => '600',
        ],
        'ollama.model_swap_delay' => [
            'legacy' => 'ollama_model_swap_delay',
            'group' => 'AI Provider',
            'label' => 'Ollama model swap delay seconds',
            'type' => 'number',
            'default' => '8',
        ],

        'ocr.mode' => [
            'legacy' => 'ocr_mode',
            'group' => 'OCR',
            'label' => 'OCR mode',
            'type' => 'select',
            'options' => ['off', 'text', 'vision_light', 'vision_full'],
            'default' => 'off',
        ],
        'ocr.requested_tag_id' => [
            'legacy' => 'ocr_requested_tag_id',
            'group' => 'OCR',
            'label' => 'OCR requested tag',
            'type' => 'number',
            'entity' => 'paperless_tag',
            'default' => '0',
        ],
        'ocr.text_model' => [
            'legacy' => 'ollama_ocr_model',
            'group' => 'AI Provider',
            'label' => 'OCR text model',
            'type' => 'text',
            'default' => 'qwen3:4b',
        ],
        'ocr.vision_model' => [
            'legacy' => 'ocr_vision_model',
            'group' => 'AI Provider',
            'label' => 'OCR vision model',
            'type' => 'text',
            'default' => 'qwen3-vl:4b',
        ],
        'ocr.vision_max_pages' => [
            'legacy' => 'ocr_vision_max_pages',
            'group' => 'OCR',
            'label' => 'Vision max pages',
            'type' => 'number',
            'default' => '3',
        ],
        'ocr.vision_dpi' => [
            'legacy' => 'ocr_vision_dpi',
            'group' => 'OCR',
            'label' => 'Vision DPI',
            'type' => 'number',
            'default' => '150',
        ],
        'ocr.context_window' => [
            'legacy' => 'ollama_ocr_num_ctx',
            'group' => 'OCR',
            'label' => 'OCR context window',
            'type' => 'number',
            'default' => '12288',
        ],
        'embedding.model' => [
            'legacy' => 'ollama_embed_model',
            'group' => 'AI Provider',
            'label' => 'Embedding model',
            'type' => 'text',
            'default' => 'qwen3-embedding:4b',
        ],
        'embedding.dimension' => [
            'legacy' => 'ollama_embed_dim',
            'group' => 'Embedding',
            'label' => 'Embedding dimension',
            'type' => 'number',
            'default' => '0',
        ],
        'embedding.context_window' => [
            'legacy' => 'ollama_embed_num_ctx',
            'group' => 'Embedding',
            'label' => 'Embedding context window',
            'type' => 'number',
            'default' => '8192',
        ],
        'embedding.max_chars' => [
            'legacy' => 'embed_max_chars',
            'group' => 'Embedding',
            'label' => 'Max document chars for embedding',
            'type' => 'number',
            'default' => '6000',
        ],
        'embedding.hybrid_search_weight' => [
            'legacy' => 'hybrid_search_weight',
            'group' => 'Embedding',
            'label' => 'Hybrid search weight',
            'type' => 'number',
            'default' => '0.7',
            'min' => '0',
            'max' => '1',
            'step' => '0.1',
            'help' => 'Blend ratio: 0.0 = keyword only, 1.0 = vector only, 0.7 = default.',
        ],

        'classification.model' => [
            'legacy' => 'ollama_model',
            'group' => 'AI Provider',
            'label' => 'Classification model',
            'type' => 'text',
            'default' => 'gemma4:e4b',
        ],
        'classification.context_window' => [
            'legacy' => 'ollama_num_ctx',
            'group' => 'Classification / Review',
            'label' => 'Classification context window',
            'type' => 'number',
            'default' => '16384',
        ],
        'classification.max_tags' => [
            'legacy' => 'classification_max_tags',
            'group' => 'Classification / Review',
            'label' => 'Max tags',
            'type' => 'number',
            'default' => '4',
        ],
        'classification.max_doc_chars' => [
            'legacy' => 'max_doc_chars',
            'group' => 'Classification / Review',
            'label' => 'Max document chars',
            'type' => 'number',
            'default' => '24000',
        ],
        'classification.context_max_docs' => [
            'legacy' => 'context_max_docs',
            'group' => 'Classification / Review',
            'label' => 'Context max docs',
            'type' => 'number',
            'default' => '5',
        ],
        'classification.context_max_distance' => [
            'legacy' => 'context_max_distance',
            'group' => 'Classification / Review',
            'label' => 'Context max distance',
            'type' => 'number',
            'default' => '0.5',
        ],
        'classification.auto_commit_confidence' => [
            'legacy' => 'auto_commit_confidence',
            'group' => 'Classification / Review',
            'label' => 'Confidence auto-commit (suspended)',
            'type' => 'number',
            'default' => '0',
            'read_only' => true,
            'help' => 'Effective value: 0. ADR-0018 temporarily suspends model-confidence writes; every classification requires manual review.',
        ],
        'classification.enable_judge_verification' => [
            'legacy' => 'enable_judge_verification',
            'group' => 'Classification / Review',
            'label' => 'Enable judge verification',
            'type' => 'bool',
            'default' => '0',
        ],
        'classification.judge_confidence_threshold' => [
            'legacy' => 'judge_confidence_threshold',
            'group' => 'Classification / Review',
            'label' => 'Judge confidence threshold',
            'type' => 'number',
            'default' => '101',
        ],
        'classification.judge_model' => [
            'legacy' => 'ollama_judge_model',
            'group' => 'AI Provider',
            'label' => 'Judge model',
            'type' => 'text',
            'default' => 'qwen3:4b',
        ],

        'worker.poll_interval_seconds' => [
            'legacy' => 'poll_interval_seconds',
            'group' => 'Worker',
            'label' => 'Poll interval seconds',
            'type' => 'number',
            'default' => '0',
            'help' => '0 disables scheduled polling.',
        ],

        'gui.base_url' => [
            'legacy' => 'gui_base_url',
            'group' => 'GUI',
            'label' => 'External base URL',
            'type' => 'url',
            'default' => '',
            'help' => 'Public ArchiBot URL used for links generated outside the web UI.',
        ],
        'gui.timezone' => [
            'legacy' => 'app_timezone',
            'group' => 'GUI',
            'label' => 'Timezone',
            'type' => 'text',
            'default' => 'Europe/Vienna',
            'help' => 'IANA timezone for displayed timestamps, e.g. Europe/Vienna.',
        ],
        'gui.date_format' => [
            'legacy' => 'gui_date_format',
            'group' => 'GUI',
            'label' => 'Date/time format',
            'type' => 'text',
            'default' => 'dd.mm.yyyy hh:mm:ss',
            'help' => 'Timestamp display format. Supported tokens: dd, mm, yyyy, hh, MM, ss (default: dd.mm.yyyy hh:mm:ss).',
        ],

        'webhook.secret' => [
            'legacy' => 'webhook_secret',
            'group' => 'Webhook',
            'label' => 'Webhook secret',
            'type' => 'password',
            'default' => '',
            'sensitive' => true,
            'help' => 'Required for webhook ingress and write-only after saving. A stored value takes precedence over deployment configuration. Leave blank to keep the current value.',
        ],
        'webhook.log_raw_body' => [
            'legacy' => 'webhook_log_raw_body',
            'group' => 'Webhook',
            'label' => 'Log raw webhook body',
            'type' => 'bool',
            'default' => '0',
        ],

        'mcp.transport' => [
            'legacy' => 'mcp_transport',
            'group' => 'MCP',
            'label' => 'Transport',
            'type' => 'select',
            'options' => ['stdio', 'sse', 'streamable-http'],
            'default' => 'stdio',
        ],
        'mcp.port' => [
            'legacy' => 'mcp_port',
            'group' => 'MCP',
            'label' => 'Port',
            'type' => 'number',
            'default' => '3001',
        ],
        'mcp.host' => [
            'legacy' => 'mcp_host',
            'group' => 'MCP',
            'label' => 'Host',
            'type' => 'text',
            'default' => '0.0.0.0',
        ],
        'mcp.enable_write' => [
            'legacy' => 'mcp_enable_write',
            'group' => 'MCP',
            'label' => 'Enable write tools',
            'type' => 'bool',
            'default' => '0',
            'help' => 'Global kill switch for mutating MCP tools. Per-user Laravel MCP tokens are managed under /settings/mcp-tokens.',
        ],
        'mcp.api_key' => [
            'legacy' => 'mcp_api_key',
            'group' => 'MCP',
            'label' => 'Legacy API key',
            'type' => 'password',
            'default' => '',
            'sensitive' => true,
            'help' => 'Legacy static MCP auth key. Prefer Laravel-managed per-user MCP tokens. Write-only after saving.',
        ],
        'mcp.laravel_auth_enabled' => [
            'legacy' => 'mcp_laravel_auth_enabled',
            'group' => 'MCP',
            'label' => 'Use Laravel MCP tokens',
            'type' => 'bool',
            'default' => '1',
            'help' => 'Validate MCP tool tokens through Laravel archibot:mcp-token-verify.',
        ],
        'mcp.laravel_path' => [
            'legacy' => 'mcp_laravel_path',
            'group' => 'MCP',
            'label' => 'Laravel app path',
            'type' => 'text',
            'default' => '/app/laravel',
            'help' => 'Path to the Laravel app used by the Python MCP runtime for local token verification.',
        ],
        'mcp.laravel_php_binary' => [
            'legacy' => 'mcp_laravel_php_binary',
            'group' => 'MCP',
            'label' => 'Laravel PHP binary',
            'type' => 'text',
            'default' => 'php',
            'help' => 'PHP executable used by the Python MCP runtime to run the Laravel token verifier.',
        ],
        'mcp.classify_rate_limit' => [
            'legacy' => 'mcp_classify_rate_limit',
            'group' => 'MCP',
            'label' => 'Classify rate limit per hour',
            'type' => 'number',
            'default' => '10',
        ],

        'audit.retention_days' => [
            'legacy' => null,
            'group' => 'Audit',
            'label' => 'Audit retention days',
            'type' => 'number',
            'default' => '7',
        ],
    ],
];
