"""Canonical event names for the event-driven pipeline."""

WEBHOOK_RECEIVED = "webhook.received"
WEBHOOK_DUPLICATE = "webhook.duplicate"
WEBHOOK_NORMALIZED = "webhook.normalized"
ACTOR_STARTED = "actor.started"
ACTOR_SUCCEEDED = "actor.succeeded"
ACTOR_FAILED = "actor.failed"
ACTOR_RECOVERED_STALE = "actor.recovered_stale"
ACTOR_RETRY_SCHEDULED = "actor.retry_scheduled"
PIPELINE_BLOCKED_EMBEDDING_NOT_READY = "pipeline.blocked.embedding_index_not_ready"
PIPELINE_START_PENDING = "pipeline.start.pending"
PIPELINE_START_COALESCED = "pipeline.start.coalesced"
PIPELINE_START_ATTACHED = "pipeline.start.attached"
PIPELINE_FORCE_REPROCESS_REQUESTED = "pipeline.force_reprocess.requested"
PIPELINE_UNBLOCKED_EMBEDDING_READY = "pipeline.unblocked.embedding_index_ready"
PIPELINE_CANCELLED = "pipeline.cancelled"
DOCUMENT_ACTOR_READY = "document.actor.ready"
DOCUMENT_FETCHED = "document.fetched"
DOCUMENT_CLASSIFIED = "document.classified"
DOCUMENT_REVIEW_SUGGESTION_STORED = "document.review_suggestion.stored"
REVIEW_COMMIT_SUCCEEDED = "review.commit.succeeded"
REVIEW_COMMIT_SKIPPED = "review.commit.skipped"
DOCUMENT_PROCESSING_BLOCKED_NOT_MIGRATED = "document.processing.blocked_not_migrated"
EMBEDDING_INDEX_BUILD_STARTED = "embedding_index.build.started"
EMBEDDING_INDEX_BUILD_COMPLETED = "embedding_index.build.completed"
EMBEDDING_INDEX_BUILD_FAILED = "embedding_index.build.failed"
