#!/usr/bin/env python3
"""Generate Archify architecture diagrams as Mermaid Markdown."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / ".archify" / "diagrams.json"
TARGET = ROOT / "docs" / "architecture" / "archify.md"


def _diagram_block(diagram: dict[str, Any]) -> str:
    kind = str(diagram["kind"])
    lines = [kind]
    direction = diagram.get("direction")
    if direction:
        lines[0] = f"{kind} {direction}"

    body = diagram.get("body")
    if not isinstance(body, list) or not all(isinstance(line, str) for line in body):
        raise ValueError(f"diagram {diagram.get('id', '<unknown>')} body must be a list of strings")

    lines.extend(body)
    return "\n".join(lines)


def main() -> None:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    diagrams = source.get("diagrams")
    if not isinstance(diagrams, list) or not diagrams:
        raise ValueError(".archify/diagrams.json must contain at least one diagram")

    parts = [
        "<!-- Generated by scripts/generate_archify_diagrams.py from .archify/diagrams.json. -->",
        f"# {source['title']}",
        "",
        str(source["description"]),
        "",
        "> Nicht direkt bearbeiten: Quelle ist [`.archify/diagrams.json`](../../.archify/diagrams.json). Regenerieren mit `python3 scripts/generate_archify_diagrams.py`.",
        "",
        "## Diagramme",
        "",
    ]

    for diagram in diagrams:
        diagram_id = diagram["id"]
        title = diagram["title"]
        summary = diagram["summary"]
        parts.extend(
            [
                f"### {title}",
                "",
                f"Archify-ID: `{diagram_id}`",
                "",
                summary,
                "",
                "```mermaid",
                _diagram_block(diagram),
                "```",
                "",
            ]
        )

    TARGET.write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    main()
